### ISSUE TITLE
Keeping the tunnel open uses 100% of the CPU

### ISSUE THREAD

**Issue by rubik** [nkconnor/ngrok#2]
Example to reproduce:

```rust
use ngrok;

fn main() -> std::io::Result<()> {
    let tunnel = ngrok::builder()
        .http()
        .port(3030)
        .run()?;

    let public_url = tunnel.https()?;

    println!("Tunnel is open at {:?}", public_url);

    std::thread::sleep(std::time::Duration::from_secs(10));

    println!("Exiting");
    Ok(())
}
```

While the main thread is sleeping, 100% of a CPU is used. Since the `ngrok` binary does not do this, and that the main thread is sleeping, the only possibility is that this library somehow uses 100% of the CPU.

**Comment by rubik** [comment]
I think this is caused by this loop:

https://github.com/nkconnor/ngrok/blob/master/src/lib.rs#L232-L254

which checks if the `ngrok` process is still running. I think it should check at periodic intervals, like 10 seconds or more, not to use 100% of a CPU. And even then, does it really need to check? If the tunnel is not available anymore the client that will make the request to the tunnel URL will get an error.

**Comment by nkconnor** [comment]
Thanks for the report. I’d like to keep the check in place that anytime a URL is handed out it is at that moment believed to be valid and the tunnel open.

I wonder if we can get rid of the thread/loop altogether and kill the proc in `impl Drop`. There’s not much other mechanics going on other than that right now. I’ll have to peak at the `std::process` docs and see how safe we are using the API in `impl Drop`. Using a sleep or something is an easy fix to include if your CPU is being hammered though

**Comment by rubik** [comment]
But when the `http()` or `https()` methods are called the status is already checked, so it's still true that whenever a URL is handed out it is believed to be valid. Isn't it enough to make it clear in the docs that whenever you need the URL, you should call these methods?

I am running this on a Raspberry Pi and hammering the CPU is a real problem. If you don't want to get rid of the loop, what about making it configurable? For my use-case keeping the match expression to wait in the channel without the loop would be enough.

**Comment by nkconnor** [comment]
> But when the http() or https() methods are called the status is already checked, so it's still true that whenever a URL is handed out it is believed to be valid. Isn't it enough to make it clear in the docs that whenever you need the URL, you should call these methods?

These methods were checking the status by polling a channel from within that `loop` in question. The loop was sending a message if the process exited.

Checkout PR #3 and let me know if this works for you. It drops the loop entirely and also adds `http_unchecked` if you don't want to do any syscalls (checking the proc status). Also, cool that you are running this on a Pi. Is there anything missing in the library that'd be useful for you?

**Comment by nkconnor** [comment]
`0.5.0` is published w/ these changes if you want to give it a run

**Comment by rubik** [comment]
Great, thanks for the quick turnaround! I'll test tomorrow and will let you know.

> Also, cool that you are running this on a Pi. Is there anything missing in the library that'd be useful for you?

This library has everything I need. I use it as an easy way to reach the Pi from the outside without having to set up a static IP. It's working great!

**Comment by rubik** [comment]
I tested it on the Raspberry Pi and it works perfectly, thanks a lot! I can close this issue now.
