### ISSUE TITLE
ngrok v3 provides only https

### ISSUE THREAD

**Issue by guizEn** [nkconnor/ngrok#7]
Hello,

It seems this crate does not work with version 3 of ngrok.  
Version 3 does not provide http any more (only https).  

I'm new in RUST, but I tried to update your lib to make it works with ngrok v3 :
[lib.zip](https://github.com/nkconnor/ngrok/files/9010530/lib.zip)

Regards,

**Comment by nkconnor** [comment]
thanks for the report - this should be fixed in the latest release (0.6.0). please let me know if you have any issues
